### ISSUE TITLE
SFX - Give Detailed DrillDown about Partition/ Stateless Instance Count by Node

### ISSUE THREAD

**Issue by alburgin** [microsoft/service-fabric-explorer#115]
I work in a 200+ person development team, with stateful and stateless services running on  a service fabric cluster.  In our cluster we have a few different node types and > 200 services.  The service fabric explorer UX gives a summary for the cluster of the total number of services and replicas.  It would be useful to us if we could drill in and have it also show:
1.  The total number of stateless instances we have and on which node types. 
2.  How many stateful services we have on each node type.
3. The total number of stateful service partitions we have per node type.

Recently we wanted this information because we were evaluating service fabric resource governance (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-resource-governance), 
 for services not in containers. We needed to determine if we have enough cores for each service to be allocated a core without running out cores.  This is important because the service fabric documentation recommends against having services which are governed and non-governed on the same set of nodes. Additionally, you cannot allocate fewer than 1 core per service. Before we turned on service fabric governance for all services, (granting each process a core) we needed to ensure we had enough cores for all services. Otherwise, per the documentation, we run the risk of not having enough cores, which results in some services not being placed by service fabric.

Additionally, if we end up turning resource governance for all services we will need to monitor this data on an ongoing basis, to ensure that as more services are written, we continue to have enough cores in our cluster to support them.  With a very large development team, and a microservices architecture, it is impossible to track each new service that is added - having a global dashboard would make this much easier.  

This feature would also be valuable for other similar decisions in the future, as it is very difficult to make data driven decisions without being able to easily collect the correct data.

Thanks!
Alex

**Comment by MikkelHegn** [comment]
Thanks for this Alex.

I remember @tonglingchen  and I were discussing search capabilities in the treeview (or in general). One of our conclusions was that we would probably need an api on the server side to support this.

There are multiple ways we could do this:
1. Ask for the prodcut to have it buildt in the mangement endpoint.
2. Create a service which exposes these apis and make an extension for SFX to disaply the cluster stats.

@tonglingchen: How far along is the extension model for SFX to be able to explore that path?

For an intermediate solution, using the follwoign apis, might help you get the data:
- https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getclusterhealthchunk
- EventStore api's

**Comment by MikkelHegn** [comment]
#103 and #102 for reference as there might be some cluster statistics / metadata api we could use for all these cases.
