### ISSUE TITLE
Add functionality to move primary/secondary replica

### ISSUE THREAD

**Issue by oanapl** [microsoft/service-fabric-explorer#119]
Add ... next to the replicas with option to move the primary/secondary to another node. Useful for mitigation and for testing some scenarios.

![image](https://user-images.githubusercontent.com/11232790/45638641-9db13d80-ba62-11e8-9f11-b3f81e13849a.png)

**Comment by MikkelHegn** [comment]
Are you considering this API?: https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-removereplica

We would need confirmation dialog with this in red :-)

> There are no safety checks performed when this API is used. Incorrect use of this API can lead to data loss for stateful services.

Is the ForceRemove flag implicit, optional or not supported here? I would love to enable it, but it should be a separate action, maybe on the confirmation dialog, with a second warning.

**Comment by jeffj6123** [comment]
It looks like the command https://docs.microsoft.com/en-us/powershell/module/servicefabric/move-servicefabricprimaryreplica?view=azureservicefabricps and https://docs.microsoft.com/en-us/powershell/module/servicefabric/move-servicefabricsecondaryreplica?view=azureservicefabricps would be the proper way to handle moving the replicas, but as of right now the functionality for these are not exposed by http endpoints.
