### ISSUE TITLE
Group Services in SFX UI

### ISSUE THREAD

**Issue by EVMartinez** [microsoft/service-fabric-explorer#128]
Good morning Team,

The following is a feature that a some of my customers have requested and when I mention that to others they agreed that will be useful:

**Scenario:** Service Fabric as an institutional platform for the organization.
Multiple teams deploying their applications to the cluster

**Issue:** Quickly group the applications that belong to a specific team

**Current Workaround:** In namespace of the application define the team that own the service (not quite useful in practice)

**Proposed Feature:** Allow grouping application by Team or whatever string they define to group the services like the following (in SFX):

Applications:
----FinancialTeam:
-------Company.Product.Invoicing
-------Company.Product.DebtCalculation
-------Company.Product.Loans
----MarketingTeam:
-------Company.Product.Campaigns
-------Company.Product.MktCore
----PeopleTeam:
-------Company.Product.NewHiresProcess

What do you think?

**Comment by MedAnd** [comment]
Wondering if this could be expanded & implemented as [Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

_Labels enable users to map their own organizational structures onto system objects in a loosely coupled fashion, without requiring clients to store these mappings._

PS. Assume SF Mesh would also support this ☺️

**Comment by MikkelHegn** [comment]
For Mesh in Azure, these can be tagged using ARM as they are all ARM resources. We are considering labels in the platform and we should tie in to that for the proposed SFX experience.

I think for now implementing namespace paths in the app uri seems like a reasonable solution.
