### ISSUE TITLE
SF Explorer App doesn't prompt for user credentials

### ISSUE THREAD

**Issue by pdraughan** [Microsoft/service-fabric-explorer#130]
Hello,
When I visit my SF cluster via a web browser (https://subdomain.domain.com:19080), users are prompted to provide their AAD credentials. They are then provided access (and read or admin) based on their membership in our connected AAD apps. However, when I connect to the same cluster(s) via the SF Explorer app (tested today with v. 18.9.2701), users are NOT prompted for credentials and instead are passed into a SF Explorer Shell where they are correctly and repeatedly told that getting cluster, node, and application health fails.
Is there a configuration/modification I am to make to the HTML/JS files that I've missed that requires/prompts users for their AAD credentials?

**Comment by tonglingchen** [comment]
What was the exact URL you used in the SFX Standalone APP?

**Comment by pdraughan** [comment]
https://prod.avenel.com:19080

**Comment by pdraughan** [comment]
Mind you, we have that address IP restricted and requiring a certification, so I don't expect you to be able to replicate my experience directly. When someone visits their explorer via the SF Explorer App, does it ask for authentication?

**Comment by tonglingchen** [comment]
I am not clear about that "require a certification" part. So if you visit in web browser directly, does it prompt to select a certificate?

**Comment by pdraughan** [comment]
Yes. The certificate validation occurs after the AD authentication. In a browser, users are required to authenticate; via the SF Explorer app, authentication is bypassed. I had the SF Explorer app available as a RemoteApp tool to internal staff, but since the app updated, users are no longer prompted for credentials; however, forcing an older version installation didn't fix the experience. I see within the app (C:\Program Files (x86)\Microsoft\ServiceFabricExplorer\resources\app\utilities\auth) there seems to be a js call to AAD, but I don't see if being executed after the Module > prompt.connect-cluster page(s)?

**Comment by tonglingchen** [comment]
I have verified with v18.9.2701 by connecting to a cluster with AAD auth - it worked fine. There is a known issue though - AAD silent sign in does not work with Standalone APP and it will just show a blank page when AAD silent sign in happens. 
There has been no change to the auth workflow since previous release. Can capture some screenshots of the auth workflow both in browser and app?

**Comment by pdraughan** [comment]
I have tried on three different computers (two in Azure, one local) and the experience remains the same...I can open SF explorer via web (sign in prompted), but not with the SF Explorer app. I'm on SF 6.3.187.9494.
https://screencast.com/t/LK0LyH4ZgtFP 
I'm perplexed why in the SF App there isn't even a sign in/My account box in the top right corner.

**Comment by tonglingchen** [comment]
Thank you @pdraughan. I have made a[ private build](https://1drv.ms/u/s!Aq_B4fTRa2tthCuDiFTlJH1yyVpe) which will open devtools by default. Please unzip, run, and capture a short video for the network traffic panel.

**Comment by pdraughan** [comment]
Morning!
I took a quick clip to first show that a normal IE 11 browser can get to the SF Explorer, then running your private build, I took a look at the Console and Network tools. If there is further information you wish I had provided in the clip, do please let me know.
https://screencast.com/t/F9mjgwimHpH
I have started looking into what that "net::ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY" is all about, but it seems to be a reference to IIS, which I have not altered on the SF Cluster, and further begs the question of differing experience between web and app. I do hope that helps your brain, as I remain confused. Thanks for the help!

**Comment by tonglingchen** [comment]
Thank you! Instead of IE11, you can try use latest Chrome to connect to your cluster and you may see same issue. 
Can you check your cluster cert to see if it uses one of blacklisted cipher? [https://http2.github.io/http2-spec/#BadCipherSuites](https://http2.github.io/http2-spec/#BadCipherSuites)

**Comment by pdraughan** [comment]
My apologies for the delay, it took a bit to prep and test. Thank you greatly for the insight. We did have a bad cipher suite involved in our cluster. Removing that bad apple allows the SF Explorer app to again connect to our cluster. No issue on the app's part.
Sorry/Thanks!
