### ISSUE TITLE
Accessing Service Fabric Cluster: AADSTS50058: A silent sign-in request was sent but no user is signed in.

### ISSUE THREAD

**Issue by Tadimsky** [microsoft/service-fabric-explorer#148]
I repeatedly get the following error when trying to access the Service Fabric Explorer for my clusters:

> **error**
> login_required
> 
> **error_description**
> AADSTS50058: A silent sign-in request was sent but no user is signed in.
>  Trace ID: d7c6a70e-5f5b-4542-bb68-b7f41a780600
>  Correlation ID: 67eba14f-5fa4-4785-b88d-d3e7bc4b0d29
>  Timestamp: 2018-11-07 07:14:37Z
> 
> **state**
> 5c87e4ca-48e0-41d2-bebf-1958e7be00bc|3abaf302-28ab-4a24-b005-423ed9090e7c

Can the explorer handle this request and not try to do silent sign-in? I would hope that it would redirect me to the AAD login page to get new credentials.

**Comment by Tadimsky** [comment]
Looks like this may be tracked by #106 

Although it does not work for me if I close and re-open the browser. I have to sign in on some other site (like Azure Portal) in order for it to work.

**Comment by tonglingchen** [comment]
Yes same issue with #106. I do have a plan to **fix* this in near future. 

*since this issue comes from the adal itself so the fix will be some hacking workaround.*
