### ISSUE TITLE
Service Fabric Explorer just loads blank white page and requires refresh to load

### ISSUE THREAD

**Issue by MikeChristensen** [microsoft/service-fabric-explorer#194]
The first time I load SFX, I just get a blank white page.  I have to hit CTRL+F5 one or two times to get it to load.  When it doesn't load, I see this in my console:

![image](https://user-images.githubusercontent.com/6528426/58666746-13a3bf00-82e9-11e9-8640-6c01e008841c.png)

Browser info:

Google Chrome | 74.0.3729.169 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Windows 10 OS Build 17763.503
JavaScript | V8 7.4.288.28

**Comment by jeffj6123** [comment]
Hello,

What version of service fabric are you running?

**Comment by MikeChristensen** [comment]
Current fabric version
6.4.658.9590

**Comment by jeffj6123** [comment]
Are there specific pages of the site where this happen or does it happen for all pages? Also how often does this happen?

**Comment by MikeChristensen** [comment]
I've only tried this for `/Explorer/index.html#/` since that's what I have saved in my bookmarks..  It happens 100% of the time.  I go to that location, I see a blank white page, I hit CTRL+F5 to refresh, and the site continues to work from that point on.  Next time I go to the site in a new browser session, same thing.

**Comment by jeffj6123** [comment]
Do you have the same thing happen if you visit just <clusterurl>:19080?

**Comment by MikeChristensen** [comment]
Yes.  Same thing.

**Comment by jeffj6123** [comment]
Do you see this with any other clusters you view or just this one?

**Comment by MikeChristensen** [comment]
Every single one..  We have a dev and staging environment setup, and I've setup several of my own test clusters.  The issue happens on all.

**Comment by tudorsibiu90** [comment]
I have also experienced this for months. Shame on me for not reporting it, but it is so annoying...

**Comment by jeffj6123** [comment]
@MikeChristensen , @tudorsibiu90  do you know which versions you started seeing this happening in? also @tudorsibiu90 are you getting the same error in your developer console?

**Comment by MikeChristensen** [comment]
Not sure, I've been using SF for probably a year or so now, and it's always happened..

**Comment by jeffj6123** [comment]
Hey,
So Service fabric 6.5 is going to be rolled out shortly and could potentially fix your issue. So I would be curious to see if you continue to have this issue once you are on 6.5 and if so we can follow up in official channels to set up a way to further diagnose this.

**Comment by MikeChristensen** [comment]
Sounds good!!  I'll try again once 6.5 is released..

**Comment by olivergrimes** [comment]
I'm also having this issue in Chrome, multiple times a day on multiple clusters.

The workaround for me seems to be:

F12/Dev Tools > Application > Local Storage > Clear

That does the trick every time.  Hopefully it's already fixed in the update mentioned.

**Comment by MikeChristensen** [comment]
@olivergrimes CTRL+F5 should work as well..

**Comment by olivergrimes** [comment]
@MikeChristensen That has never worked for me - still doesn't!

**Comment by MikeChristensen** [comment]
6.5 made things WAY worse!  Now this happens no matter what, and a CTRL+F5 won't fix it.  SFX is completely broken now.  Why was this update ever released?

**Comment by jeffj6123** [comment]
@MikeChristensen are you still getting the same error or a different error?

**Comment by MikeChristensen** [comment]
Yup, same error as the stack trace above (cannot read selectTreeNode of undefined).  Confirmed clearing local storage works.

**Comment by tudorsibiu90** [comment]
this is only happening in Chrome as far as I can see and it is so frustrating I cannot even begin to describe it. This has been an issue for a year now as I have also reported it multiple times. I cannot believe it's still not fixed.

**Comment by MikeChristensen** [comment]
I've been using the new Edge (Which is also based on Chromium engine) and it repros there too.

**Comment by mhofkens** [comment]
same here... this has been an issue since the beginning of service fabric.
Service Fabric version 6.5.641.9590

**Comment by jeffj6123** [comment]
Hey, 
As an update on this issue the fix that should hopefully remove these issues was not in 6.5 CU1 but is in for 6.5 CU2.

**Comment by MikeChristensen** [comment]
That's good to know!  Is there a release date planned?  This bug is driving me nuts!

**Comment by dannyfhalpotia** [comment]
Any update on expected release date?

**Comment by jeffj6123** [comment]
Sorry for a very slow update. But 6.5 CU2 has been getting rolled out currently which should hopefully resolve these issues.

**Comment by MikeChristensen** [comment]
@jeffj6123 Can you tell us the build number for this version?  (6.5.???.????)

**Comment by jeffj6123** [comment]
The version would be 6.5.658.9590

**Comment by cbogles** [comment]
Hi, it seems the latest release solved the issue for us. Now a simple refresh is enough, thanks!!

**Comment by jeffj6123** [comment]
I am going to keep this issue open a little longer to see if anyone else continues to have issues @MikeChristensen  @olivergrimes  @tudorsibiu90 If you guys can report back when you have upgraded aswell.

**Comment by mhofkens** [comment]
Our dev cluster is running 6.5.658.9590 and works great. Thanks for fixing this.

**Comment by olivergrimes** [comment]
@jeffj6123 - Our clusters are now on 6.5.658.9590.  Looking good so far!  Thanks for the fix 👍

**Comment by tudorsibiu90** [comment]
@jeffj6123 Same here. It works now. Thank you!

**Comment by MikeChristensen** [comment]
@jeffj6123 Also confirmed this works.  You probably have to clear your browser cache after the upgrade thought.

**Comment by jeffj6123** [comment]
I will be closing the issue now. @MikeChristensen that could be true, it shouldnt need to be cleared but that extra precaution could help.
