### ISSUE TITLE
Is it possible to use a customised version of SFE with Azure?

### ISSUE THREAD

**Issue by frackham** [microsoft/service-fabric-explorer#220]
This project allows us to fork, amend and create a customised version of SFE (i.e remove / add UI functionality).

If we wanted to create an amended version of the UI (to effectively piggyback off this work to create a more specific admin portal), am I right in thinking there's no way for this to be used instead of the SFE within Azure?

_(obviously onus would be on us to incorporate updates/changes)._

**Comment by jeffj6123** [comment]
As of right now we do not have a native solution exposed. In theory you could create a service that serves a custom version of this.
