### ISSUE TITLE
Improve Load information readability

### ISSUE THREAD

**Issue by jeffj6123** [microsoft/service-fabric-explorer#248]
1. remove the double title "Load information" is displayed twice.
2. Adding help text links or (?) icons to further add more information explaining metrics.
2.5 Specifically add a way to clarify the -1 value for some metrics.

**Comment by DianeHadley** [comment]
Also potentially filtering out the 3 deprecated properties so they don't appear in the table (NodeLoad, NodeRemainingCapacity, and NodeRemainingBufferedCapacity)
