### ISSUE TITLE
Beta SF Explorer issue with AAD authentication

### ISSUE THREAD

**Issue by DavidBastide** [microsoft/service-fabric-explorer#289]
Hi,

I have a cluster configured with AAD authentication (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-setup-aad#create-azure-ad-applications-and-assign-users-to-roles), recently updated to Fabric version 7.1.409.9590.
When I try to use the SF Explorer beta: https://mycluster.com:19080/Explorer/beta.html, it authenticates through the native AAD application with redirect_uri=https://mycluster:19080
I get an error saying AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '<my native application id>'.

If I add https://mycluster:19080 to the native AAD app's redirect URLs, the error disappears, but https://mycluster:19080 redirects me to https://mycluster.com:19080/Explorer/index.html, so I never reach beta...

Thanks,
David

**Comment by jeffj6123** [comment]
Hey,

Sorry about the inconvenience but this should be fixed shortly.
there was an issue with 7.1 release but has been fixed for the first CU.  It was fixed here #271

**Comment by DavidBastide** [comment]
Ok thanks, I'm closing the issue then, and I'll wait for the CU :-)
