### ISSUE TITLE
Incorrect message about reliability level

### ISSUE THREAD

**Issue by raunakpandya** [microsoft/service-fabric-explorer#291]
![image](https://user-images.githubusercontent.com/18751774/82950739-78106180-9fc3-11ea-91b0-39e0936d282f.png)

If for some reason SFX is unable to load the node and the count of the client side is 0 (as nodes failed to load) there is a warning which pops up saying you cluster is running at Bronze durability even if the cluster is running with Silver or higher. This confuses the admin further. We need to handle the error case here and fix.

**Comment by jeffj6123** [comment]
Yeah, SFX will check how many nodes there are when the cluster essentials loads and will wait for the node's data to finish loading but im guessing when it hits an error and cant load the nodes at first then it is assuming an empty length.
