### ISSUE TITLE
ReplicaId is not enough Information to easily track down issues

### ISSUE THREAD

**Issue by KDSBest** [microsoft/service-fabric-explorer#294]
Currently in the service fabric explorer if a cluster upgrade is waiting for a reconfiguration or safety check only a replica id is provided like:

_backend_1 | PreUpgradeSafetyCheck | {"SafetyCheck":{"Kind":"WaitForReconfiguration","PartitionId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}}

Depending on your setup and number of services/applications it is not easy to find out, which application is the issue. It will be awesome if next to PartitionId is the Application Name and Service Type.

**Comment by jeffj6123** [comment]
This should be pretty doable using
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getservicenameinfo and
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getapplicationnameinfo
