### ISSUE TITLE
GetClusterManifest 503 error

### ISSUE THREAD

**Issue by moldyseaswimmer** [microsoft/service-fabric-explorer#297]
http://localhost:19080/$/GetClusterManifest?api-version=3.0&_cacheToken=1591619884960
{"Error":{"Code":"E_ABORT","Message":"Operation canceled."}}

standalone setup beta interface

**Comment by jeffj6123** [comment]
was this a recurring issue and only happened with the beta version?

**Comment by moldyseaswimmer** [comment]
A series of uninstall/reinstall seems to have resolved this.
