### ISSUE TITLE
Error when unprovision app versions

### ISSUE THREAD

**Issue by gnegno84** [microsoft/service-fabric-explorer#309]
When using the Unprovision option to remove unused App Type versions, after correctly entering the name/version of the type to confirm the operation, first i don't get any feedback (as the button still states "Unprovision") then after few seconds i get two error notifications (see attachment)
Reloading the page shows that the app type version have been correctly removed.

![Annotazione 2020-06-18 130356](https://user-images.githubusercontent.com/23550305/85013116-53438000-b164-11ea-939a-1b58a079f0ed.png)

**Comment by jeffj6123** [comment]
It appears that some actions attempt to get called twice.
