### ISSUE TITLE
Alphabetically sort node names when they are added to the cluster.

### ISSUE THREAD

**Issue by milope** [microsoft/service-fabric-explorer#432]
**Is your feature request related to a problem? Please describe.**

When scaling out the VMSS and the nodes proceed to join the SFX, the area appended to the end of the "Nodes" tree view instead of retaining the alphabetic sorting of the view, requiring a full page refresh to restore the storing.

**Describe the solution you'd like**

Is there a chance the new nodes could be auto-alphabetically sorted when they are added to the cluster?

**Additional context**

**Comment by jeffj6123** [comment]
@milope  what version are you seeing this on?

**Comment by milope** [comment]
@jeffj6123 7.1.458.9590 at least in SFX.
