### ISSUE TITLE
Sort columns alphanumerically

### ISSUE THREAD

**Issue by JRBANCEL** [Microsoft/service-fabric-explorer#44]
It would be nice if SFX was sorting columns containing numbers alphanumerically.
For example, [versions ](https://imgur.com/a/V30wr) and [node ID](https://imgur.com/a/SgxAj).

Semantically, it should be FE_1, FE_2, ..., FE_10, FE_11, not FE_1, FE_10, FE_11, ..., FE_2.

**Comment by tonglingchen** [comment]
I totally agree this is very nice to have. However the node naming does not follow a fixed format so it would be hard for UI to handle all the cases. 

Closing...

**Comment by JRBANCEL** [comment]
What is a scenario where the nodes are not named **<Prefix><NumericalSuffix>**?
Even then, the point is that it is this is the case for 99.99% of the customers.

**Comment by rishirsinha** [comment]
Point Tom is raising is that the node naming is not a fixed format, not that the nodes will not have name and hence handling it might be hard, specially in the UX. The FE_1 format comes from the fact that Azure names the VMs that way. On non-azure infrastructure it might be named differently. If we do want to have these features, it should not be at the UX level rather the core product should sort things the correct way and UX should display it as such.
