### ISSUE TITLE
Starting SFX without internet connectivity throws an error

### ISSUE THREAD

**Issue by MikkelHegn** [Microsoft/service-fabric-explorer#49]
When starting SFX without internet connectivity the following javascript error is thrown:

![image](https://user-images.githubusercontent.com/12242001/39265558-68c9982c-487c-11e8-8abf-dbdd5fa1939c.png)

You get past the error and can run SFX.
SFX should show a user friendly error message.

**Comment by tonglingchen** [comment]
Not seeing this anymore.
