### ISSUE TITLE
Repair Jobs - Phase view collapses on refresh

### ISSUE THREAD

**Issue by a-santamaria** [microsoft/service-fabric-explorer#502]
**Describe the bug**
On Repair Jobs tab if the phases are expanded for a job they collapse on refresh. Also If you are in Full Description it switches to Condensed on refresh.

**To Reproduce**
- Go To Beta view
- Set refresh on
- Go to Repair Jobs Tab
- Open one of the jobs and expand the phases or go to full description

**Expected behavior**
Stay in the same view without collapsing items and update values if necessary.

**Screenshots**

###### Before refresh
![image](https://user-images.githubusercontent.com/7062665/111829129-85c40a00-88a9-11eb-97e5-49299c57650e.png)

###### Before refresh
![image](https://user-images.githubusercontent.com/7062665/111829190-9aa09d80-88a9-11eb-89de-830810ff719b.png)

###### Before refresh
![image](https://user-images.githubusercontent.com/7062665/111829272-b2782180-88a9-11eb-8929-77caea6b0ac5.png)

###### Before refresh
![image](https://user-images.githubusercontent.com/7062665/111829285-b60ba880-88a9-11eb-98e4-85e2a1e09cb2.png)

 -  Service Fabric version Any
 - OS(for browser not SF) Any
 - Browser/ Browser version [e.g. chrome, safari] Any

**Additional context**

**Comment by jeffj6123** [comment]
Hey @a-santamaria  this should be fixed in the 7.2 CU5
https://github.com/microsoft/service-fabric-explorer/pull/459
