### ISSUE TITLE
Beta SFX issues

### ISSUE THREAD

**Issue by LukeSlev** [microsoft/service-fabric-explorer#516]
**Describe the bug**
Copy buttons on Node essentials page do not copy the value but rather the path to the property (eg. instead of FE you get node.raw.Type)

Also in service details page the table for service placement policies has the titles and values flipped ie. the value for type falls under domain name and vice versa

**To Reproduce**
Deploy a service on a cluster and check out the Node essentials page for any node and check out the service details page of a service that has a service placement policy.

**Expected behavior**
The copy buttons on the node essentials page should copy the actual value and not the property name and the table for service placement policy should have the titles matched with the values correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/28886212/114472605-65852380-9ba7-11eb-9e99-83ed640d459b.png)
- Copy button issue

![image](https://user-images.githubusercontent.com/28886212/114472678-8f3e4a80-9ba7-11eb-825e-b7ae8be71485.png)
- Table/value issue

 -  Service Fabric version
 code version: 7.1.428.9590
 - OS(for browser not SF)
 OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19042 Build 19042

 - Browser/ Browser version [e.g. chrome, safari]
Microsoft edge Version 89.0.774..75 (Official build 64 bit)

**Additional context**

**Comment by jeffj6123** [comment]
Hello,

thanks for bringing this up.
both of these should be fixed in later versions, by the following pull requests and fixed by the latest updated version of 7.2

https://github.com/microsoft/service-fabric-explorer/pull/344
https://github.com/microsoft/service-fabric-explorer/pull/466
