### ISSUE TITLE
Update in progress does not show progress by domain

### ISSUE THREAD

**Issue by davidelettieri** [microsoft/service-fabric-explorer#525]
**Describe the bug**
When updating an application in service fabric in the update in progress view, I usually can see the progress. In the beta nothing is shown.

**To Reproduce**
Upgrade an application

**Expected behavior**
I expected to see something similar to this
![image](https://user-images.githubusercontent.com/5262655/115367862-d8555680-a1c6-11eb-9df2-0beef90f98fc.png)

**Screenshots**
This is what I saw
![image](https://user-images.githubusercontent.com/5262655/115367560-9af0c900-a1c6-11eb-9319-32372f34e8cb.png)

 -  Service Fabric version 8.0.514.9590
 - Microsoft Windows [Version 10.0.19041.685]
 - Chrome 89.0.4389.128

**Comment by jeffj6123** [comment]
Thank you for noticing this,
the following PR will address this issue
#526 
THis fix should become available with the next critical Update for 8.0
