### ISSUE TITLE
Auto refresh does not work in SFX beta

### ISSUE THREAD

**Issue by laithhisham** [microsoft/service-fabric-explorer#527]
**Describe the bug**
Looks like the auto refresh is not working properly in the SFX Beta version

**To Reproduce**
Mainly observed while upgrading applications. The refresh indicator shows that a refresh is done but the upgrade state doesn't progress until manually refreshing the web page

**Expected behavior**
Auto refresh should update the details of the upgrade and the whole SFX details in general

**Screenshots**
![image](https://user-images.githubusercontent.com/49263932/115673309-29935080-a355-11eb-80c1-0068d4d7058a.png)

After refreshing manually right after that
![image](https://user-images.githubusercontent.com/49263932/115673354-3748d600-a355-11eb-97a7-a442b0e62db0.png)

 -  Service Fabric version: 8.0.514.9590
 - OS(for browser not SF): Windows
 - Browser/ Browser version [e.g. chrome, safari]: Microsoft Edge version 90.0.818.39

**Comment by laithhisham** [comment]
@jeffj6123 looks like it is only happening when an application/service is upgrading. The other events seem to be refreshing fine, but only when an application is updating the auto refresh does not seem to be working both in the main page and in the app page itself. Only when clicking the refresh button manually the state gets updated. And it only happens in Beta, when leaving beta it works as expected

**Comment by jeffj6123** [comment]
@laithhisham going off the screenshots im guessing it was at least 3 minutes between when you visited the page and when you manually refreshed?

**Comment by laithhisham** [comment]
@jeffj6123 true, I waited for a few minutes before manually refreshing

**Comment by jeffj6123** [comment]
so after some investigation it looks like the page level refresh might not get added if there was an error hit during the first refresh attempt.
