### ISSUE TITLE
SFXBeta - Tried "UnprovisionType" it is not working properly

### ISSUE THREAD

**Issue by mohandatla** [microsoft/service-fabric-explorer#529]
I use "UnprovisionType" to clean up image store occasionally, it is working fine SFX but when I trying in SFX Beta it is not showing update status even when I tried auto refresh or manual refresh.

On low note, we are in process of enabling the policy until that using command lets & SF explorer as work around.

**Comment by jeffj6123** [comment]
@mohandatla what kind of errors are you seeing? are you saying that after hitting unprovision type that it still shows up after refreshing?

**Comment by nezuko-cc** [comment]
Same here - I also encountered the same issue. In my case there is no error or any message showing up after clicking "Unprovision Type". From explorer it just looked like nothing happened.

**Comment by retainjason** [comment]
Same here ... switching out of the Beta, the option to unprovision a type does work.
Did also notice the prompt for confirmation asks for the version number as part of the message, whereas the Beta one does not.

**Comment by keyrox** [comment]
Can confirm, same here.
