### ISSUE TITLE
Not seeing upgrade progress by domain

### ISSUE THREAD

**Issue by enemaerke** [microsoft/service-fabric-explorer#553]
**Describe the bug**
In the old UI, on the "upgrades in progress" tab, I could tell how far each upgrade was progressing by seeing the progress by upgrade domains. This column is now empty for me:

**To Reproduce**
Navigating to /Explorer/Index.html#/apps/upgrades when upgrading an application and observe the "Progress by Upgrade Domain" column being empty. 

**Expected behavior**
I was expecting the upgrades domains to be shown in this column for the application upgrades (as in the now old version and as they are shown in the individual application view)

**Screenshots**
![image](https://user-images.githubusercontent.com/448060/120611385-6c683e00-c454-11eb-92c8-dbb19e176c76.png)

 -  Service Fabric version: 8.0.516.9590
 - OS(for browser not SF): Windows 10
 - Browser/ Browser version [e.g. chrome, safari]:91.0.4472.77 (Official Build) (64-bit)

**Additional context**
No additional context

**Comment by starforce** [comment]
Progress by upgrade Domain does not update when a node has been upgraded in Beta SFX. The first screen capture is from the Production Version of SFX and the second one is from the Beta version of SFX. I

Production

<img width="1789" alt="Screen Shot 2021-06-10 at 5 02 40 PM" src="https://user-images.githubusercontent.com/4247353/121599266-cd71b200-ca10-11eb-8284-31edae7cac6f.png">

Beta


<img width="1923" alt="Screen Shot 2021-06-10 at 5 02 07 PM" src="https://user-images.githubusercontent.com/4247353/121599349-ebd7ad80-ca10-11eb-8296-1590348aa353.png">
