### ISSUE TITLE
SFExplorer Beta - does not refresh contents of the page

### ISSUE THREAD

**Issue by zendu** [microsoft/service-fabric-explorer#573]
I have an app page open. When a deployment is triggered using ARM, the page shows deployment progress. If the page is already open before deployment begins the page does not refresh deployment progress. Refresh duration is set to 30 seconds in top right corner. I had to refresh entire page to start seeing deployment progress.

**Comment by jeffj6123** [comment]
@zendu can you try visiting the details tab and then back to the essentials? This seems to help it refresh correctly, we are working on a fix for this. it appears that some pages are not refreshing correctly as expected

**Comment by WhitWaldo** [comment]
Expanding on this ticket further, I find that refreshes don't reflect changes to application and services made independently of SFX. For example, when looking at an application in SFX, if I remove a service via Powershell and a refresh runs (manual or auto), I'd expect that the service should no longer be listed under that app. Rather, it will persist until I navigate to another page and come back (or refresh the page in the browser).

This is true also of the elements in the left navigational tree - they will not reflect changes either until either re-expanded or the browser itself is refreshed.

**Comment by jeffj6123** [comment]
this should be fixes as of 8.1 CU1
