### ISSUE TITLE
Filter popups in SFX beta don't show up properly

### ISSUE THREAD

**Issue by smflorentino** [microsoft/service-fabric-explorer#591]
**Describe the bug**
Filtering health evaluations, services, and service types don't work in the new UX:

**To Reproduce**
Open SFX, open an application, try to filter on various things.

**Expected behavior**
Filtering popups work

**Screenshots**
![image](https://user-images.githubusercontent.com/3495150/127241771-0f73fd77-377e-4b66-9a36-7d15769fcab3.png)

 -  Service Fabric version 8.0.514.9590
 - OS(for browser not SF) Windows Server 2019
 - Browser/ Browser version [e.g. chrome, safari] Chrome

**Additional context**

**Comment by jeffj6123** [comment]
should be fixed as of 8.1 cu1
