### ISSUE TITLE
Issues with Repair Jobs in SFX Beta

### ISSUE THREAD

**Issue by smflorentino** [microsoft/service-fabric-explorer#592]
**Describe the bug**
This is both a bug and a feature request.
Bug: Full Description of SFX repair jobs are blank.
Feature request: Repair jobs do not include parity with desktop SFX (I expect to see current UD in the condensed view)

**To Reproduce**
Open an active Repair Job in SFX.
**Expected behavior**
Feature request: I'd prefer to see current UD for Preparing, Executing, Restoring.
Bug: Job Info and Full description are blank.

**Screenshots**
Feature request:
![image](https://user-images.githubusercontent.com/3495150/127242055-3516a17b-8988-49f9-964a-dc5196fab0fc.png)

Bugs:
![image](https://user-images.githubusercontent.com/3495150/127242074-887f59b0-05ac-46f6-9b71-cb29eda290e6.png)
![image](https://user-images.githubusercontent.com/3495150/127242096-923079f5-2a4f-4a5f-a491-d8523bec53f9.png)

 -  Service Fabric version 8.0.514.9590
 - OS(for browser not SF) Windows
 - Browser/ Browser version [e.g. chrome, safari] Chrome

**Additional context**

**Comment by jeffj6123** [comment]
@smflorentino hey for that job, if its still running. are you able to open the dev tools to see if there are any errors? This seems a big suspicious because normally that information is provided inside the executor data.

**Comment by smflorentino** [comment]
@jeffj6123 - opened feature request in separate issue. Per our offline discussion, is a fix out?
