### ISSUE TITLE
Confirmation prompts breaks the user experience

### ISSUE THREAD

**Issue by FredrikDahlberg** [microsoft/service-fabric-explorer#641]
**Describe the bug**
Confirmation prompts breaks the user experience.

**To Reproduce**
Unprovision a type or delete a service.

**Expected behavior**
A normal confirmation prompt.

**Additional context**
Typically you only remove services this way during development when the Service Fabric cluster is corrupted.

**Comment by FredrikDahlberg** [comment]
> 
> 
> @FredrikDahlberg can you explain a little more about the issue you experience?

What is there more to explain. When you try to delete something you get a confirmation prompt. You have to type in the name of the resource to continue. It serves no purpose and breaks the feature and the UX. Just replace it with a normal confirmation prompt. As if SF is not cumbersome enough already to work with.

**Comment by strabu** [comment]
I find that very annoying too that I have to copy-paste the name of the resource over and over again.
Especially on (local) dev cluster this feature is more annoying than life-saving.

**Comment by jeffj6123** [comment]
closing this issue as we have no plans to remove the confirmation modals.

**Comment by FredrikDahlberg** [comment]
> 

Well, the issue is not about removing the modals! It is about making the modals actually work properly.
