### ISSUE TITLE
Cannot see how full cluster is anymore in Cluster Metrics

### ISSUE THREAD

**Issue by nokjuh** [microsoft/service-fabric-explorer#652]
**Describe the bug**
In the old Service Fabric Explorer, it was possible to select "Normalize metric data" in Cluster Metrics. This displayed at a glance how full the cluster is compared to the maximum. Also mousing over a node showed how full it was compared to the maximum, both with percentage and in metric used/maximum.

These are both missing in the new Service Fabric Explorer. This makes it harder to see how much of the cluster capacity is used.

**To Reproduce**
Cluster => Metrics => Select a metric, e.g. Reserved MemoryInMB

Try to see how full nodes are compared to the maximum capacity.

**Expected behavior**
It should be possible to select "Normalize metric data" like in old SFX.
It should be possible to mouse over a node and see info like in old SFX, e.g. "_nt1vm_0: 12288 / 13925 (88.2 %)".

 -  Service Fabric version: 8.2.1235.9590
 - OS(for browser not SF): Windows 10
 - Browser/ Browser version: Chrome 96.0.4664.45 64-bit

**Additional context**
Workaround: "View old SFX"

**Comment by jeffj6123** [comment]
Hey, this is being fixed with the following PR soon
#665
