### ISSUE TITLE
Unprovision Type does not work on the new interface

### ISSUE THREAD

**Issue by A-Lynch** [microsoft/service-fabric-explorer#656]
Unprovision Type does not work on the new interface

**To Reproduce**

1. Delete a service using the UI
2. Delete a type using the UI

**Expected behavior**
The type is deleted

The only way to delete the type is to revert to the non Beta UI

**Comment by calebsmith411** [comment]
Reporting the same issue.

**Comment by tophallen** [comment]
also ran into this issue

**Comment by sedwardstx** [comment]
reporting same issue, you can alternatively remove type using PowerShell cmdlet Unregister-ServiceFabricApplicationType

**Comment by jeffj6123** [comment]
fixed with 9.0
