### ISSUE TITLE
Show more health check duration info during upgrades

### ISSUE THREAD

**Issue by smflorentino** [microsoft/service-fabric-explorer#714]
**Is your feature request related to a problem? Please describe.**
Really like the improvements to cluster repair tasks showing the breakdown and duration for each phase. However, for app upgrades, that information is still missing.

**Describe the solution you'd like**
Show the time spent (and remaining) for app upgrade health checks. Right now the UI doesn't give any indication of progress.

This could even be a % process bar based on time remaining, right under "Time left until timeout" - could say something like "Time left until health check stable duration completes" (which would reflect how long the app health has been stable, resetting appropriately if app becomes unhealthy)

**Additional context**
Would like more visual feedback on % time remaining for health checks:
![image](https://user-images.githubusercontent.com/3495150/165948173-c936d71f-6476-464d-9ff6-8adae8c39516.png)

**Comment by jeffj6123** [comment]
Hey, @smflorentino currently SFX is constrained by the runtime not providing this information. but I absolutely agree. The health stable and wait duration should both be visualized for complete insight into the state of an upgrade. I will push this request to the runtime to see if they can look at adding this information.
