### ISSUE TITLE
Arrow Icon in Collapsible  Cards on Service Fabric Explorer Page is Misleading

### ISSUE THREAD

**Issue by musaugurlu** [microsoft/service-fabric-explorer#718]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem but an enhancement of UX

**Describe the solution you'd like**
The collapsible information cards in Service Fabric Explorer have a down-arrow when they are collapsed and an up-arrow when expanded. Many websites and UI frameworks show a down-arrow when an accordion menu or card is expanded and a right-arrow when collapsed. If the SF Explorer can follow the same approach, It will be easier for users to adopt it. 

**Additional context**
![image](https://user-images.githubusercontent.com/18178232/166982136-61ecc2ce-5253-4e59-a9dc-9c6b97ebd4cc.png)

**Comment by jeffj6123** [comment]
@musaugurlu can you link to where you commonly see that? Bootstrap follows the same design pattern https://getbootstrap.com/docs/5.0/components/accordion/ and material does aswell
https://material.angular.io/components/expansion/overview
