### ISSUE TITLE
SFE notification appears off screen

### ISSUE THREAD

**Issue by micfulton-msft** [microsoft/service-fabric-explorer#720]
**Describe the bug**
SFE application notifications are shifted off the screen so they can't be read.

**To Reproduce**
When using a laptop connected to a monitor the notification appears off screen with just the corner of the notification visible. No text is visible. There is only 1 display active with the laptop lid shut and Display Settings confirms this. (not a multi monitor situation)

To view the notification, I need to open the laptop and generate the notification again.

**Expected behavior**
The notification displays properly.

**Screenshots**
![error](https://user-images.githubusercontent.com/102943493/168669081-10a885e6-22a2-4ce8-8171-ac1b2e2cc1b6.png)

(This is the very bottom right corner of my screen. I can't scroll the notification in any way.)

 -  Service Fabric version v7.2.522.9590
 - OS(for browser not SF) Windows 11
 - Browser/ Browser version [e.g. chrome, safari] Not applicable but I use Edge

**Additional context**

**Comment by jeffj6123** [comment]
hey @micfulton-msft this appears to for the desktop exe which is not handled in this repo. I would say you could reach out to justin moran for where to log this issue.
