### ISSUE TITLE
We cant scale service to more then 9 instances

### ISSUE THREAD

**Issue by ArthNRick** [microsoft/service-fabric-explorer#777]
**Describe the bug**
I can't scale service instances for more than 9 on version "9.0.1048.9590".

**To Reproduce**
Click on "Scale Service" and type 10 or more units

**Expected behavior**
My cluster has 30 VMs, so i should to be able to scale to more then 9 instances

**Screenshots**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/17991046/190836985-b55d9be0-757a-4608-bbf8-d3bf9a54517d.png)
New version disabled button

![MicrosoftTeams-image](https://user-images.githubusercontent.com/17991046/190836993-599b2bb6-757e-40d5-be1e-09b1f2f85acc.png)
Previous version enabled button

-  Service Fabric version: 9.0.1048.9590
- OS(for browser not SF): Windows
- Browser: Edge, Chrome and Firefox has this problem

**Additional context**
On 8.1.337.9590 version this is possible. When we had updated the cluster to  "9.0.1048.9590" Version, we loose this possibility

**Comment by WhitWaldo** [comment]
@jeffj6123 This issue can probably be closed following the recent merge.
