### ISSUE TITLE
Sorting Events grid by Timestamp does nothing

### ISSUE THREAD

**Issue by abatishchev** [microsoft/service-fabric-explorer#782]
**Describe the bug**

Clicking on the Timestamp column of the application's Events page doesn't sort the grid. Clicking on other columns does.

**To Reproduce**

Go to `https://<url>:19080/Explorer/index.html#/apptype/<app type>/app/<app name>/events`

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/351644/193085880-5b886b17-a2b8-444d-b6c0-2e42a727a6e1.png)

![image](https://user-images.githubusercontent.com/351644/193085961-1cfa5048-fa5d-4580-9d7b-f991b8533b40.png)

 -  Service Fabric version: 9.0.1048.9590
 - OS (for browser not SF): Windows 10
 - Browser/ Browser version; Edge 105.0.1343.50 

**Additional context**

SFRP cluster in Public cloud.

**Comment by WhitWaldo** [comment]
@jeffj6123 This issue can probably be closed following the recent merge.
