### ISSUE TITLE
Service Creation UI Radio Buttons Broken

### ISSUE THREAD

**Issue by messnerdev** [microsoft/service-fabric-explorer#792]
**Describe the bug**
Service creation UI radio buttons are broken

**To Reproduce**
Attempt to create a service manually from the `Service Types` section of an Application page

**Expected behavior**
Radio buttons for `Service Package Activation Mode` only allow selecting SharedProcess or ExclusiveProcess, but not both.
Radio buttons for PartitionScheme only allow selecting a single partition scheme, not all 4. Selecting a specific partition scheme should prompt for additional input related to that partition scheme. Int64Range specifically should prompt for Count, LowKey, and HighKey

**Screenshots**
![image](https://user-images.githubusercontent.com/46359640/200919892-1b1a0fa5-db11-472b-a4e2-2a58cd886a03.png)

 - Service Fabric version: 9.1.1390.9590
 - ClientOS: Windows 10
 - ClientBrowser: Latest Chrome and Latest Edge

**Comment by messnerdev** [comment]
This is what it used to look like:
![Items](https://user-images.githubusercontent.com/46359640/200924338-6652b109-c41d-4a0f-a489-383477859dd1.png)

**Comment by jeffj6123** [comment]
@messnerdev hey thanks for pointing this out. it looks like the library we used for some of the UI removed their radio button component.

**Comment by jeffj6123** [comment]
#797
