### ISSUE TITLE
Durability tier warning when using availability zones

### ISSUE THREAD

**Issue by williamoconnorme** [microsoft/service-fabric-explorer#796]
**Describe the bug**
After upgrading to service fabric 9.1.1390.9590, service fabric explorer shows a warning for node types stating that less node type instances exist in the cluster for the configured durability tier when availability zones are enabled, even though the minimum number of nodes are present in the node type

**To Reproduce**
1. Deploy or upgrade cluster to 9.1.1390.9590.
2. Deploy node type with the following configuration
   - Durability tier: Silver
   - Instance count: 15
   - Availability zones: 3
   - Zone Balance: true
   - OS SKU: 2022-Datacenter

3. Check service fabric explorer overview to view warning

**Expected behavior**
Warning should not be displayed when the minimum number of nodes deployed for each zone satisfy the minimum number of VMs for each availability zone for the configured durability tier

**Screenshots**
Screenshot of warning banner
![image](https://user-images.githubusercontent.com/978081/201781227-1404c470-157c-465c-96ee-492f8deaf6f6.png)

Screenshot displays cluster map of impacted node type
![image](https://user-images.githubusercontent.com/978081/201780621-d00c6380-173e-4f76-a057-07534a982244.png)

**Additional context**
- We run multiple clusters but are currently testing node types with availability zones. This only appears to affect our silver durability tier node type which has 3 availability zones set and 15 node type instances (5 nodes per zone).
- The clusters service Fabric zonal upgrade mode is set to an empty string which defaults to hierarchical upgrade mode
- The clusters VMSS zonal upgrade mode is set to parallel.
- The clusters reliability tier is set to Platinum

**Comment by jeffj6123** [comment]
hey this is going to be fixed with 9.1 CU 1
