### ISSUE TITLE
Use UTC time checkbox is inverted

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric-explorer#810]
**Describe the bug**
In the "Recent Application and Container Exit Event Reasons" section, if you check the "Use UTC time" box, it uses local time, if you uncheck the box, it uses UTC time.

**To Reproduce**
Check and uncheck the box.

**Expected behavior**
Checking a box labeled "Use UTC time" should result in times being displayed in UTC.

SF version 9.1.1390.9590
Browser: Edge 107.0.1418.62

**Comment by jeffj6123** [comment]
fixed in newest CU
