### ISSUE TITLE
Cluster treeview navigation is really difficult with keyboard and screen reader

### ISSUE THREAD

**Issue by kastwey** [microsoft/service-fabric-explorer#834]
Hello,

I am a blind engineer. I am currently working at Microsoft, and as part of my daily tasks, I have to use SF Explorer to monitor and troubleshoot SF clusters in production.

The problem is that the treeview used to navigate the various nodes / applications in the cluster has serious accessibility issues.

To navigate through a treeview, we are supposed to use the arrow and navigation keys (home, end, page up and page down, or even the letters) to perform operations on it: expand / collapse nodes, and move through the different nodes in the tree.
However, in this treeview, the only way to move through the tree and expand or collapse nodes is by using the tab key, which contravenes these best practices. A treeview should be perceived as a single control within the navigation tree when pressing tab.

Why is this so important?

Imagine a cluster with three hundred nodes. If I want to get to the last node, the only way to do this currently is to press the tab key more than 600 times, because for each node, the focus stops on the name, and then on the expand or collapse button for that node.
Also, when nodes are paginated, there is no way to change pages using the keyboard, which means that if my node is too far down the list, I can never reach it.

[You can see an excellent implementation of an accessible treeview on this web site](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/)

Please, could you solve this issue as soon as possible? Actually it is very hard to have to work with this tool being blind.

Thanks in advance.

Best regards,

Juanjo.

**Comment by jeffj6123** [comment]
@kastwey  absolutely. we will look into this immediately. We do periodic accessibility testing with the c+ai org but it sounds like the current experience is insufficient for working with the tree view so we will work at getting all of the arrow key based navigation working fully as expected. I believe we should currently have the arrow keys: up, down, left and right working currently.

**Comment by chensation** [comment]
@kastwey This should be released along with 9.1 cu 5

**Comment by kastwey** [comment]
Hi, guys.

Just to tell you that TreeView navigation is great! I am working this
week continuously with SF Explorer for some migrations, and you can't
even imagine the difference. In short, before I would have had to ask
for help to be able to work on this task, because of the extreme
slowness of navigation, and now I am 100% autonomous.

For someone like me, for whom the accessibility of a service means the
difference between having an insurmountable barrier or being able to
work on equal terms with his colleagues, this change is a huge step...
So that's why I'm writing this comment, just to say: thank you for the
effort to solve this issue! :)

Happy sunday! :)


2023-05-17 19:38 GMT+01:00, chensation ***@***.***>:
