### ISSUE TITLE
Question - does SFx supports onpremise AD Authentication ?

### ISSUE THREAD

**Issue by nareshkhatri81** [Microsoft/service-fabric-explorer#84]
Hi Team,
Does SFx supports onpremise AD Authentication or windows integrated authentication ?

Thanks,
Naresh Khatri

**Comment by stevshan** [comment]
Hi Naresh,

SFX Standalone supports AD/Windows Auth on Windows.
SFX inside the cluster depends on the browser. If the browser supports AD/Windows challenge, then SFX can work as expects.

Thanks,
Steven

**Comment by stevshan** [comment]
Hi Naresh,

SFX itself doesn't have any authentication/authorization. The authentication/authorization is based on the cluster security settings. For more information on how the security works in Service Fabric cluster, please refer to [Client-to-node Security](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security#client-to-node-security).

Thanks.
Steven.

**Comment by nareshkhatri81** [comment]
@stevshan 
Thanks for sharing that info.
Documentation seems to be confusing.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-windows-security

Client-to-node security is configured by using ClientIdentities. To establish trust between a client and the cluster, you must configure the cluster to know the client identities that the cluster can trust. You can establish trust in two different ways:

Specify the domain group users that can connect.
Specify the domain node users that can connect.

Specify the domain group users that can connect. does this means it allows AD group ? or what they meant by domain group users ?

Thanks,
naresh Khatri

**Comment by MikkelHegn** [comment]
@nareshkhatri81 - yes that is being applied to SFX as well, as the authorization for SFX is done by the Service Fabric HTTP management endpoint.

**Comment by stevshan** [comment]
@nareshkhatri81 - Please take the answer from MikkelHegn as reference. If you still have any question, please open a new issue or reopen this one if it's related. Thanks.
