### ISSUE TITLE
replica endpoint address broken hyperlink?

### ISSUE THREAD

**Issue by skyiky** [microsoft/service-fabric-explorer#844]
**Describe the bug**
broken hyperlink

**Screenshots**
![image](https://user-images.githubusercontent.com/19918150/235743917-3325c0e5-2ee7-4a01-867c-00078b37a28a.png)

 -  Service Fabric version:  9.1.1653.9590
 - OS(for browser not SF): MS Edge
 - Browser/ Browser version [e.g. chrome, safari] Version 112.0.1722.68 (Official build) (64-bit)

**Additional context**

**Comment by jeffj6123** [comment]
@skyiky this should be fixed with 9.1 cu5
