### ISSUE TITLE
SFX: Endpoint Urls are not clickable.

### ISSUE THREAD

**Issue by coyesiku** [microsoft/service-fabric-explorer#859]
The endpoint urls in the details of an app are no longer clickable due to a missing href attribute.

This occurs when using the Path though the Applications menu or through the Nodes menu and navigating down to the instance and it's endpoints

![image](https://github.com/microsoft/service-fabric-explorer/assets/125588045/0bd4b1c0-1c39-46e3-b473-3f4f88151970)

Current version:
![image](https://github.com/microsoft/service-fabric-explorer/assets/125588045/31404fa0-f56f-40de-b967-a984d525073a)

**Comment by jeffj6123** [comment]
@coyesiku this should be fixed in the next update.
