### ISSUE TITLE
Repair Job Timestamps are incorrect

### ISSUE THREAD

**Issue by jacksontromero** [microsoft/service-fabric-explorer#861]
**Describe the bug**
Repair Jobs are displayed with incorrect timestamps that are nonsensical and mismatched with the actual object data.

**To Reproduce**
Create a Service Fabric Repair Job using the SDK or PowerShell cmdlets.  Claim and Prepare the task, wait for it to be Approved by Repair Manager, then Execute and Restore it.  Once completed, examine the timestamps for those states.  Examine the underlying timestamps by querying for the completed task (again either SDK or PowerShell) and inspecting them or by using "Copy raw repair Job" in SFE.

**Expected behavior**
The timestamps should match between the underlying data and SFE.

**Screenshots**
##### SFE Screenshot
![image](https://github.com/microsoft/service-fabric-explorer/assets/42822986/76c20d71-a9dc-47ae-8465-a0831f853b49)
##### Logged Output
![image](https://github.com/microsoft/service-fabric-explorer/assets/42822986/25d18d4d-16a9-49ed-bc30-04e87bdbba4d)
##### Result from "Copy raw repair Job":
```
{
	"Scope": {
		"Kind": "Cluster"
	},
	"TaskId": "4cad3309-eeca-4a0f-a5b4-2b2c4e641b19",
	"Version": "133322765903969334",
	"Description": "Benchmark node _Node_2",
	"State": "Completed",
	"Flags": 0,
	"Action": "Benchmark",
	"Target": {
		"Kind": "Node",
		"NodeNames": [
			"_Node_2"
		]
	},
	"Executor": "_Node_2",
	"ExecutorData": "",
	"Impact": {
		"Kind": "Node",
		"NodeImpactList": [
			{
				"NodeName": "_Node_2",
				"ImpactLevel": "Pause"
			}
		]
	},
	"ResultStatus": "Succeeded",
	"ResultCode": 0,
	"ResultDetails": "",
	"History": {
		"CreatedUtcTimestamp": "2023-06-26T18:09:50.396Z",
		"ClaimedUtcTimestamp": "2023-06-26T18:10:24.663Z",
		"PreparingUtcTimestamp": "2023-06-26T18:10:24.745Z",
		"ApprovedUtcTimestamp": "2023-06-26T18:10:40.068Z",
		"ExecutingUtcTimestamp": "2023-06-26T18:11:34.931Z",
		"RestoringUtcTimestamp": "2023-06-26T18:11:54.398Z",
		"CompletedUtcTimestamp": "2023-06-26T18:11:54.662Z",
		"PreparingHealthCheckStartUtcTimestamp": "2023-06-26T18:10:24.830Z",
		"PreparingHealthCheckEndUtcTimestamp": "2023-06-26T18:10:24.899Z",
		"RestoringHealthCheckStartUtcTimestamp": "2023-06-26T18:11:54.542Z",
		"RestoringHealthCheckEndUtcTimestamp": "2023-06-26T18:11:54.601Z"
	},
	"PreparingHealthCheckState": "Skipped",
	"RestoringHealthCheckState": "Skipped",
	"PerformPreparingHealthCheck": false,
	"PerformRestoringHealthCheck": false
}
```

 -  Service Fabric version 9.1.1799.9590
 - SF SDK version 6.1.1799.9590
 - Windows 11 Enterprise, build 22621.1848
 - Edge

**Comment by jeffj6123** [comment]
@jacksontromero thank you for spotting this. It looks like it was introduced in the previous version and a fix is currently being handled.
