### ISSUE TITLE
The list of nodes should clearly indicate the seed nodes

### ISSUE THREAD

**Issue by oanapl** [microsoft/service-fabric-explorer#96]
The left hand side tree should have a different icon (or an extra indicator) for seed nodes, so it's easy to detect them at a glance. 
Additionally, the search in left side tree can highlight the seed nodes when searching "seed".

**Comment by tonglingchen** [comment]
Or we can add a column to the Node list. Users can filter the node list based on true/false value of this column. 
Also, it should be better to add a ? link for seed node to explain what it is.
